### PR TITLE
Add the abstract, authors, and affiliations

### PR DESCRIPTION
**Pull request by leouieda**
## Notes

* Session: Open-source software for near-surface geophysics and its applications
* Maximum 2000 characters
* Introduce the project
* What the software can do
* Lessons learned throughout our experience with publicly releasing research code
* How the open-source project could grow and be maintained

---

This was a stab at the abstract. The notes above reflect what the conveners indicated would fit the session. I'm entire sure what the format will be but from what I can tell:

* Short live (virtual) presentation with a Q&A
* Long recorded presentation (we can post to YouTube I guess)

Feedback is more than welcome and feel free to add yourselves to the authors list 🙂

### CODE REVIEW

**Comment by leouieda** [comment]
I'm not super happy with the title so please make suggestions.

**Comment by aguspesce** [comment]
@leouieda, maybe something like: What have we learned in 11 years developing Fatiando a Terra project?

**Comment by leouieda** [comment]
@aguspesce and then the abstract just says "Not much." 😆 

Jokes aside, I like that idea but it still doesn't solve my main issue with the title: It doesn't really communicate what we've learned. I tend to like titles that inform readers so that people learn something just from reading it. But I don't know if we can do that here since the message is a bit more hazy.

**Comment by LL-Geo** [comment]
@leouieda I'm thinking something like: From a general package to several specialized tools, the development of the Fatiando a Terra project in the past 11 years (might need some better words in here)
Or Towards the engagement of the modern ecosystem, the development of the Fatiando a Terra project in the past 11 years
Or The Fatiando a Terra project towards the engagement of the modern ecosystem in the past 11 years

**Comment by leouieda** [comment]
Going from @aguspesce's suggestion, I started thinking "what **have** we learned?" To me, it boils down to:

1. Thinking deeply about design and usability helps build software that can grow steadily
2. Prioritizing usability over speed (of code and development) is a better use of core developer time
3. Having an open door is not enough to get people involved, we have to actively welcome them in

In terms of development, 1 and 2 are pretty similar but I couldn't condense them into one. 

Can anyone think of a way to tie these into some of the suggestions from @LL-Geo?

**Comment by santisoler** [comment]
Hi everyone! This opportunity at AGU is great!

Regarding the title I have two main thoughts:
1. Setting it as a question or as a sentence, they both work very well! (I think I prefer the question, though). I would just remove the amount of years, it's a datum that isn't that important to be in the title. I don't see anyone reading it and saying "wow, 11 years, I would totally listen that talk, is not like they were only 9 years".
2. I gave a talk back in 2019 called "Experiencias en el Desarrollo de Fatiando a Terra" (Experiences in the development of Fatiando a Terra). Most of the people in that meeting weren't on geosciences, so they didn't have a clue about Fatiando. Therefore they would just read "Experiences in the development of yada yada yada": not a very interesting talk. So, I would say: if we expect the attendees to know or have heard about Fatiando before, the current title (or the @aguspesce proposal) would caught attention. If not, maybe we should pitch it into a more detailed description of what the talk would be about and how it can be interesting for any attendee.

**Comment by leouieda** [comment]
How about:

"Design useful tools that do one thing well and work together: rediscovering the UNIX philosophy while building the Fatiando a Terra project"

It's not relying on people knowing what Fatiando is and says a bit about what we're gonna talk about.

**Comment by leouieda** [comment]
@aguspesce @santisoler @LL-Geo please post your full name and affiliation here so I can add you to the abstract (if you'd like, of course).

**Comment by leouieda** [comment]
Actually, merging this in and making a new PR for the title. Please feel free to send a PR adding your full name and affiliation or comment here and I'll be happy to add you 🙂  The more the merrier!

**Comment by RichardScottOZ** [comment]
You could slip the domain  in after if you wanted...Fatiando...geophysics project

**Comment by leouieda** [comment]
Thanks for the suggestion @RichardScottOZ! Since this is AGU, we would have to be more specific about what we mean by geophysics. And at that point the title becomes an abstract 🙂 There is a proposal for a new title in #2 and feel free to add yourself to #3 as well.

**Pull request merged**
